// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LucasLCabral/payment-service/internal/ledger (interfaces: PaymentCreatedProcessor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/payment_created_processor_mock.go -package=mocks . PaymentCreatedProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ledger "github.com/LucasLCabral/payment-service/pkg/ledger"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentCreatedProcessor is a mock of PaymentCreatedProcessor interface.
type MockPaymentCreatedProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCreatedProcessorMockRecorder
	isgomock struct{}
}

// MockPaymentCreatedProcessorMockRecorder is the mock recorder for MockPaymentCreatedProcessor.
type MockPaymentCreatedProcessorMockRecorder struct {
	mock *MockPaymentCreatedProcessor
}

// NewMockPaymentCreatedProcessor creates a new mock instance.
func NewMockPaymentCreatedProcessor(ctrl *gomock.Controller) *MockPaymentCreatedProcessor {
	mock := &MockPaymentCreatedProcessor{ctrl: ctrl}
	mock.recorder = &MockPaymentCreatedProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCreatedProcessor) EXPECT() *MockPaymentCreatedProcessorMockRecorder {
	return m.recorder
}

// ProcessPaymentCreated mocks base method.
func (m *MockPaymentCreatedProcessor) ProcessPaymentCreated(ctx context.Context, evt *ledger.PaymentCreatedEvent, traceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPaymentCreated", ctx, evt, traceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPaymentCreated indicates an expected call of ProcessPaymentCreated.
func (mr *MockPaymentCreatedProcessorMockRecorder) ProcessPaymentCreated(ctx, evt, traceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPaymentCreated", reflect.TypeOf((*MockPaymentCreatedProcessor)(nil).ProcessPaymentCreated), ctx, evt, traceID)
}
