apiVersion: v1
kind: Secret
metadata:
  name: postgres-payment-credentials
type: Opaque
stringData:
  username: "payment_user"
  password: "payment_pass"
  database: "payment_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-ledger-credentials
type: Opaque
stringData:
  username: "ledger_user"
  password: "ledger_pass"
  database: "ledger_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: "rabbit_user"
  password: "rabbit_pass"
  uri: "amqp://rabbit_user:rabbit_pass@rabbitmq:5672/"
