// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LucasLCabral/payment-service/internal/api-gateway/ws (interfaces: ConnRegistry)
//
// Generated by this command:
//
//	mockgen -destination=mocks/conn_registry_mock.go -package=mocks . ConnRegistry
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	websocket "github.com/gorilla/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockConnRegistry is a mock of ConnRegistry interface.
type MockConnRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockConnRegistryMockRecorder
	isgomock struct{}
}

// MockConnRegistryMockRecorder is the mock recorder for MockConnRegistry.
type MockConnRegistryMockRecorder struct {
	mock *MockConnRegistry
}

// NewMockConnRegistry creates a new mock instance.
func NewMockConnRegistry(ctrl *gomock.Controller) *MockConnRegistry {
	mock := &MockConnRegistry{ctrl: ctrl}
	mock.recorder = &MockConnRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnRegistry) EXPECT() *MockConnRegistryMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockConnRegistry) Register(paymentID string, conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", paymentID, conn)
}

// Register indicates an expected call of Register.
func (mr *MockConnRegistryMockRecorder) Register(paymentID, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockConnRegistry)(nil).Register), paymentID, conn)
}

// RemoveIf mocks base method.
func (m *MockConnRegistry) RemoveIf(paymentID string, conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveIf", paymentID, conn)
}

// RemoveIf indicates an expected call of RemoveIf.
func (mr *MockConnRegistryMockRecorder) RemoveIf(paymentID, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveIf", reflect.TypeOf((*MockConnRegistry)(nil).RemoveIf), paymentID, conn)
}
