// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LucasLCabral/payment-service/internal/payment/repository (interfaces: Audit)
//
// Generated by this command:
//
//	mockgen -destination=mocks/audit_repository_mock.go -package=mocks github.com/LucasLCabral/payment-service/internal/payment/repository Audit
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	payment "github.com/LucasLCabral/payment-service/pkg/payment"
	gomock "go.uber.org/mock/gomock"
)

// MockAudit is a mock of Audit interface.
type MockAudit struct {
	ctrl     *gomock.Controller
	recorder *MockAuditMockRecorder
	isgomock struct{}
}

// MockAuditMockRecorder is the mock recorder for MockAudit.
type MockAuditMockRecorder struct {
	mock *MockAudit
}

// NewMockAudit creates a new mock instance.
func NewMockAudit(ctrl *gomock.Controller) *MockAudit {
	mock := &MockAudit{ctrl: ctrl}
	mock.recorder = &MockAuditMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudit) EXPECT() *MockAuditMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockAudit) Insert(ctx context.Context, tx *sql.Tx, entry *payment.AuditEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, tx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAuditMockRecorder) Insert(ctx, tx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAudit)(nil).Insert), ctx, tx, entry)
}
