// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LucasLCabral/payment-service/internal/payment/settlement (interfaces: PaymentStatusNotifier)
//
// Generated by this command:
//
//	mockgen -destination=mocks/payment_status_notifier_mock.go -package=mocks . PaymentStatusNotifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	payment "github.com/LucasLCabral/payment-service/pkg/payment"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentStatusNotifier is a mock of PaymentStatusNotifier interface.
type MockPaymentStatusNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentStatusNotifierMockRecorder
	isgomock struct{}
}

// MockPaymentStatusNotifierMockRecorder is the mock recorder for MockPaymentStatusNotifier.
type MockPaymentStatusNotifierMockRecorder struct {
	mock *MockPaymentStatusNotifier
}

// NewMockPaymentStatusNotifier creates a new mock instance.
func NewMockPaymentStatusNotifier(ctrl *gomock.Controller) *MockPaymentStatusNotifier {
	mock := &MockPaymentStatusNotifier{ctrl: ctrl}
	mock.recorder = &MockPaymentStatusNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentStatusNotifier) EXPECT() *MockPaymentStatusNotifierMockRecorder {
	return m.recorder
}

// NotifyPaymentStatus mocks base method.
func (m *MockPaymentStatusNotifier) NotifyPaymentStatus(ctx context.Context, paymentID uuid.UUID, status payment.PaymentStatus, declineReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPaymentStatus", ctx, paymentID, status, declineReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPaymentStatus indicates an expected call of NotifyPaymentStatus.
func (mr *MockPaymentStatusNotifierMockRecorder) NotifyPaymentStatus(ctx, paymentID, status, declineReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPaymentStatus", reflect.TypeOf((*MockPaymentStatusNotifier)(nil).NotifyPaymentStatus), ctx, paymentID, status, declineReason)
}
