// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LucasLCabral/payment-service/internal/payment/settlement (interfaces: TransactionRunner)
//
// Generated by this command:
//
//	mockgen -destination=mocks/transaction_runner_mock.go -package=mocks . TransactionRunner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRunner is a mock of TransactionRunner interface.
type MockTransactionRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRunnerMockRecorder
	isgomock struct{}
}

// MockTransactionRunnerMockRecorder is the mock recorder for MockTransactionRunner.
type MockTransactionRunnerMockRecorder struct {
	mock *MockTransactionRunner
}

// NewMockTransactionRunner creates a new mock instance.
func NewMockTransactionRunner(ctrl *gomock.Controller) *MockTransactionRunner {
	mock := &MockTransactionRunner{ctrl: ctrl}
	mock.recorder = &MockTransactionRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRunner) EXPECT() *MockTransactionRunnerMockRecorder {
	return m.recorder
}

// WithinTransaction mocks base method.
func (m *MockTransactionRunner) WithinTransaction(ctx context.Context, fn func(*sql.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockTransactionRunnerMockRecorder) WithinTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockTransactionRunner)(nil).WithinTransaction), ctx, fn)
}
